######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 13 22:03:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += converterWidget.h
FORMS += converterWidget.ui
SOURCES += converterWidget.cpp
